# Generated by Django 2.2.16 on 2022-08-10 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='rating',
            field=models.FloatField(null=True, verbose_name='Рейтинг'),
        ),
    ]
